type UserSubscription @model(timestamps: null) @auth(rules: [{ allow: owner }]) {
  owner: String! @primaryKey
  tier: String!
  hoursleft: Float!
  notesleft: Int
}

type Notes @model(timestamps: null) @auth(rules: [{ allow: owner }]) {
  owner: String! @primaryKey(sortKeyFields: ["timestamp"])
  timestamp: String!
  transcript: String
  note: String
  isCompleted: Boolean
}

type Subscription {
  onCreateNotesByOwner(owner: String!): Notes
    @aws_subscribe(mutations: ["createNotes"])
  
  onUpdateNotesByOwner(owner: String!): Notes
    @aws_subscribe(mutations: ["updateNotes"])
}